// ISO 22301:2019 (DIN EN ISO 22301:2020-06) — Anforderungskatalog
// Struktur pro Eintrag: { id, domain, title, q, hint }

export const DOMAINS = [
  "4. Kontext der Organisation",
  "5. Führung",
  "6. Planung",
  "7. Unterstützung",
  "8. Betrieb",
  "9. Bewertung der Leistung",
  "10. Verbesserung",
];

// Akzentfarbe je Bereich
export const DC = {
  "4. Kontext der Organisation": "#5B2D8E", // lila
  "5. Führung": "#0B3B5C", // dunkelblau
  "6. Planung": "#00C9A7", // türkis
  "7. Unterstützung": "#8DB33A", // olivgrün
  "8. Betrieb": "#47B8D4", // hellblau
  "9. Bewertung der Leistung": "#E8660A", // orange
  "10. Verbesserung": "#C0392B", // ziegelrot
};

// Helle Hintergrundvariante je Bereich
export const DC_BG = {
  "4. Kontext der Organisation": "#EDE0F5",
  "5. Führung": "#E0EAF2",
  "6. Planung": "#D6F5EE",
  "7. Unterstützung": "#EDF3D6",
  "8. Betrieb": "#D6F0F7",
  "9. Bewertung der Leistung": "#FBE7D6",
  "10. Verbesserung": "#F8DDD9",
};

export const CONTROLS = [
  // 4. Kontext der Organisation
  {
    id: "ISO22301-4.1",
    domain: "4. Kontext der Organisation",
    title: "Externe und interne Themen",
    erl: "Die Organisation muss nachweisen, dass sie systematisch analysiert hat, welche externen Faktoren (wirtschaftliches Umfeld, regulatorische Anforderungen, Marktbedingungen, gesellschaftliche Entwicklungen) und internen Faktoren (Organisationsstruktur, Ressourcen, Kultur, Prozesse) das BCMS beeinflussen. Diese Analyse muss dokumentiert und aktuell gehalten werden.",
    q: "Hat die Organisation externe und interne Themen bestimmt, die für den Zweck des BCMS relevant sind und sich auf die Erreichung der beabsichtigten Ergebnisse auswirken?",
    hint: "Prüfen Sie: Kontextanalyse, SWOT/PESTEL, Geschäftsstrategie, Protokolle der Leitungsbewertung.",
  },
  {
    id: "ISO22301-4.2.1",
    domain: "4. Kontext der Organisation",
    title: "Interessierte Parteien",
    erl: "Die Organisation muss eine vollständige Liste der für das BCMS relevanten Stakeholder erstellen und deren jeweilige Anforderungen und Erwartungen an die Aufrechterhaltung der Betriebsfähigkeit bestimmen und dokumentieren. Dazu gehören u.a. Kunden, Lieferanten, Behörden, Eigentümer und Mitarbeitende.",
    q: "Wurden die für das BCMS relevanten interessierten Parteien sowie deren relevante Anforderungen identifiziert und dokumentiert?",
    hint: "Prüfen Sie: Stakeholder-Liste, Verträge, Erwartungsmatrix.",
  },
  {
    id: "ISO22301-4.2.2",
    domain: "4. Kontext der Organisation",
    title: "Rechtliche und behördliche Anforderungen",
    erl: "Die Organisation muss einen dokumentierten Prozess etabliert haben, um alle geltenden rechtlichen, regulatorischen und behördlichen Anforderungen zu ermitteln, zu bewerten und in das BCMS zu integrieren. Das Rechtsregister muss aktuell gehalten und bei der BCMS-Umsetzung berücksichtigt werden.",
    q: "Existiert ein Prozess zur Ermittlung, zum Zugriff auf und zur Bewertung geltender rechtlicher, behördlicher und sonstiger Anforderungen, und werden diese dokumentiert, aktuell gehalten und im BCMS berücksichtigt?",
    hint: "Prüfen Sie: Rechtsregister, Compliance-Liste, Nachweis der Aktualisierung.",
  },
  {
    id: "ISO22301-4.3.1",
    domain: "4. Kontext der Organisation",
    title: "Grundlagen für den Anwendungsbereich",
    erl: "Beim Festlegen des BCMS-Anwendungsbereichs muss die Organisation nachweisen, dass sie die Kontextanalyse (4.1), die Stakeholder-Anforderungen (4.2) sowie den eigenen Auftrag, Ziele und Verpflichtungen berücksichtigt hat. Die Herleitung des Scope muss transparent und nachvollziehbar dokumentiert sein.",
    q: "Wurden bei der Festlegung des Anwendungsbereichs des BCMS die externen/internen Themen (4.1), die Anforderungen interessierter Parteien (4.2) sowie Auftrag, Ziele und Verpflichtungen der Organisation berücksichtigt?",
    hint: "Prüfen Sie: Scope-Dokument mit Begründung der Herleitung.",
  },
  {
    id: "ISO22301-4.3.2",
    domain: "4. Kontext der Organisation",
    title: "Anwendungsbereich des BCMS",
    erl: "Der Anwendungsbereich muss klar definieren, welche Organisationsteile (Standorte, Geschäftsbereiche), Produkte und Dienstleistungen eingeschlossen sind. Ausschlüsse müssen begründet sein und dürfen die BCM-Fähigkeit nicht untergraben. Das Scope-Dokument muss als dokumentierte Information vorliegen.",
    q: "Sind die einbezogenen Organisationsteile (Standorte, Grösse, Art, Komplexität) und Produkte/Dienstleistungen festgelegt, sind Ausschlüsse dokumentiert und begründet (ohne die Fähigkeit zur Aufrechterhaltung der Betriebsfähigkeit zu beeinträchtigen), und liegt der Anwendungsbereich als dokumentierte Information vor?",
    hint: "Prüfen Sie: Scope-Statement, Ausschlussliste mit Begründung.",
  },
  {
    id: "ISO22301-4.4",
    domain: "4. Kontext der Organisation",
    title: "BCMS als Ganzes",
    erl: "Die Organisation muss nachweisen, dass ein BCMS nach den Normanforderungen aufgebaut und aktiv in Betrieb ist. Dies umfasst alle geforderten Prozesse, deren Wechselwirkungen und die relevanten dokumentierten Informationen. Das System muss aktiv betrieben und fortlaufend verbessert werden.",
    q: "Wurde ein BCMS gemäss den Anforderungen der Norm aufgebaut, umgesetzt, aufrechterhalten und wird es fortlaufend verbessert, einschliesslich der benötigten Prozesse und ihrer Wechselwirkungen?",
    hint: "Prüfen Sie: Prozesslandkarte / BCMS-Handbuch.",
  },

  // 5. Führung
  {
    id: "ISO22301-5.1.a",
    domain: "5. Führung",
    title: "Führung und Verpflichtung – Ausrichtung & Integration",
    erl: "Die oberste Leitung muss aktiv und sichtbar die BCM-Politik und die BCM-Ziele vertreten und sicherstellen, dass diese mit der Unternehmensstrategie in Einklang stehen. BCM-Anforderungen müssen in alle relevanten Geschäftsprozesse integriert sein – nicht als isoliertes Projekt geführt werden.",
    q: "Stellt die oberste Leitung sicher, dass Politik und Ziele zur Aufrechterhaltung der Betriebsfähigkeit festgelegt sind, mit der strategischen Ausrichtung übereinstimmen und in die Geschäftsprozesse integriert sind?",
    hint: "Prüfen Sie: Strategiepapiere, Sitzungsprotokolle der Geschäftsleitung.",
  },
  {
    id: "ISO22301-5.1.b",
    domain: "5. Führung",
    title: "Führung und Verpflichtung – Ressourcen & Förderung",
    erl: "Die oberste Leitung muss nachweislich die notwendigen Ressourcen (Personal, Budget, Zeit) für das BCMS bereitstellen, die Bedeutung von BCM aktiv kommunizieren, fortlaufende Verbesserung fördern und andere Führungskräfte in ihrer BCM-Verantwortung unterstützen.",
    q: "Stellt die oberste Leitung sicher, dass die für das BCMS erforderlichen Ressourcen verfügbar sind, vermittelt sie die Bedeutung des BCM, fördert sie fortlaufende Verbesserung und unterstützt sie andere Führungskräfte in deren Führungsrolle?",
    hint: "Prüfen Sie: Budgetfreigaben, interne Kommunikation, Verantwortlichkeitsmatrix.",
  },
  {
    id: "ISO22301-5.2.1",
    domain: "5. Führung",
    title: "Festlegung der BCM-Politik",
    erl: "Eine formale, von der obersten Leitung genehmigte BCM-Politik muss vorliegen. Sie muss den Zweck und Rahmen des BCMS beschreiben, messbare Ziele ermöglichen, die Einhaltung relevanter Anforderungen zusichern und die Verpflichtung zur kontinuierlichen Verbesserung enthalten.",
    q: "Ist eine Politik zur Aufrechterhaltung der Betriebsfähigkeit festgelegt, die für den Zweck der Organisation angemessen ist, einen Rahmen für Ziele bietet und Verpflichtungen zur Erfüllung anwendbarer Anforderungen sowie zur fortlaufenden Verbesserung enthält?",
    hint: "Prüfen Sie: BCM-Politikdokument, Freigabevermerk der Geschäftsleitung.",
  },
  {
    id: "ISO22301-5.2.2",
    domain: "5. Führung",
    title: "Bekanntmachung der BCM-Politik",
    erl: "Die BCM-Politik muss allen Mitarbeitenden bekannt gemacht worden sein (z.B. über Intranet, Schulungen, Aushänge) und für relevante interessierte Parteien zugänglich sein. Ein Nachweis der Kommunikation muss vorliegen.",
    q: "Ist die Politik als dokumentierte Information verfügbar, innerhalb der Organisation bekanntgemacht und – soweit angemessen – interessierten Parteien zugänglich?",
    hint: "Prüfen Sie: Intranet, Schulungsunterlagen, Verteilerliste.",
  },
  {
    id: "ISO22301-5.3",
    domain: "5. Führung",
    title: "Rollen, Verantwortlichkeiten, Befugnisse",
    erl: "Alle BCM-relevanten Rollen müssen mit klaren Verantwortlichkeiten und Befugnissen definiert und besetzt sein. Dies schliesst mindestens die Rolle des BCM-Verantwortlichen und die Berichterstattung an die oberste Leitung ein. Die Zuweisung muss dokumentiert und kommuniziert sein.",
    q: "Sind Verantwortlichkeiten und Befugnisse für relevante BCM-Rollen zugewiesen, kommuniziert, und schliesst dies die Sicherstellung der BCMS-Konformität sowie die Berichterstattung an die oberste Leitung ein?",
    hint: "Prüfen Sie: Organigramm, Rollenbeschreibungen, RACI-Matrix.",
  },

  // 6. Planung
  {
    id: "ISO22301-6.1.1",
    domain: "6. Planung",
    title: "Bestimmung von Risiken und Chancen",
    erl: "Im Rahmen der BCMS-Planung müssen Risiken und Chancen identifiziert werden, die die Wirksamkeit des Managementsystems selbst (nicht Betriebsstörungen) beeinflussen. Diese beziehen sich auf die in 4.1 und 4.2 identifizierten Themen und Anforderungen und sind zu dokumentieren.",
    q: "Wurden bei der Planung des BCMS die Themen aus 4.1 und Anforderungen aus 4.2 berücksichtigt, um Risiken und Chancen zu bestimmen, die sicherstellen, dass das BCMS seine Ergebnisse erzielt, unerwünschte Effekte verhindert/verringert und fortlaufende Verbesserung erreicht wird?",
    hint: "Prüfen Sie: Risiko- und Chancenregister auf Managementsystemebene.",
  },
  {
    id: "ISO22301-6.1.2",
    domain: "6. Planung",
    title: "Umgang mit Risiken und Chancen",
    erl: "Für die identifizierten Risiken und Chancen müssen konkrete Massnahmen geplant sein, inklusive deren Integration in die BCMS-Prozesse und einer Methode zur Bewertung ihrer Wirksamkeit.",
    q: "Sind Massnahmen zum Umgang mit den identifizierten Risiken und Chancen geplant, inklusive deren Integration in BCMS-Prozesse und Bewertung ihrer Wirksamkeit?",
    hint: "Prüfen Sie: Massnahmenpläne, Verknüpfung mit 8.1 und 9.1.",
  },
  {
    id: "ISO22301-6.2.1",
    domain: "6. Planung",
    title: "Ziele zur Aufrechterhaltung der Betriebsfähigkeit",
    erl: "Die Organisation muss messbare BCM-Ziele für relevante Funktionen und Ebenen festgelegt haben. Diese müssen mit der BCM-Politik übereinstimmen, überwacht, kommuniziert und bei Bedarf aktualisiert werden. Die Ziele müssen als dokumentierte Information aufbewahrt sein.",
    q: "Sind Ziele zur Aufrechterhaltung der Betriebsfähigkeit für relevante Funktionen/Ebenen festgelegt, stehen sie im Einklang mit der Politik, sind sie messbar, werden sie überwacht, kommuniziert, bei Bedarf aktualisiert und als dokumentierte Information aufbewahrt?",
    hint: "Prüfen Sie: Zielkatalog mit KPIs, Reviewprotokolle.",
  },
  {
    id: "ISO22301-6.2.2",
    domain: "6. Planung",
    title: "Planung zur Zielerreichung",
    erl: "Für jedes BCM-Ziel muss ein konkreter Aktionsplan vorliegen, der festlegt: Was getan wird, welche Ressourcen benötigt werden, wer verantwortlich ist, bis wann es abgeschlossen sein soll und wie der Erfolg gemessen wird.",
    q: "Ist für jedes Ziel festgelegt, was getan wird, welche Ressourcen erforderlich sind, wer verantwortlich ist, wann es abgeschlossen wird und wie die Ergebnisse bewertet werden?",
    hint: "Prüfen Sie: Massnahmen-/Projektplan je Ziel.",
  },
  {
    id: "ISO22301-6.3",
    domain: "6. Planung",
    title: "Planung von Änderungen am BCMS",
    erl: "Änderungen am BCMS müssen systematisch geplant werden. Vor der Umsetzung müssen Zweck, Risiken, Ressourcenbedarf und Verantwortlichkeiten der Änderung bewertet sein. Spontane, ungeplante Änderungen am BCMS sind zu vermeiden und zu dokumentieren.",
    q: "Werden Änderungen am BCMS geplant durchgeführt, unter Berücksichtigung von Zweck und Folgen der Änderung, der Integrität des BCMS, der Ressourcenverfügbarkeit sowie der Zuweisung/Neuzuweisung von Verantwortlichkeiten?",
    hint: "Prüfen Sie: Change-Management-Protokolle für das BCMS.",
  },

  // 7. Unterstützung
  {
    id: "ISO22301-7.1",
    domain: "7. Unterstützung",
    title: "Ressourcen",
    erl: "Die Organisation muss die für das BCMS erforderlichen Ressourcen (Personal, Budget, Infrastruktur, Technologie) systematisch ermittelt haben und nachweisen, dass diese bereitgestellt werden. Dies schliesst auch Ressourcen für Übungen und die Weiterentwicklung des Systems ein.",
    q: "Wurden die für Aufbau, Umsetzung, Aufrechterhaltung und fortlaufende Verbesserung des BCMS erforderlichen Ressourcen bestimmt und bereitgestellt?",
    hint: "Prüfen Sie: Budgetplanung, Personalplanung, Investitionsentscheide.",
  },
  {
    id: "ISO22301-7.2",
    domain: "7. Unterstützung",
    title: "Kompetenz",
    erl: "Für alle Personen mit BCM-relevanten Aufgaben muss die erforderliche Kompetenz bestimmt, sichergestellt und nachgewiesen sein. Schulungs-, Qualifikations- oder Erfahrungsnachweise müssen vorliegen. Bei Kompetenzlücken müssen Massnahmen ergriffen und deren Wirksamkeit überprüft werden.",
    q: "Ist die erforderliche Kompetenz für Personen mit BCM-relevanten Tätigkeiten bestimmt, wird deren Kompetenz durch Ausbildung/Schulung/Erfahrung sichergestellt, werden bei Bedarf Massnahmen zum Kompetenzerwerb ergriffen und deren Wirksamkeit bewertet, und wird dies dokumentiert?",
    hint: "Prüfen Sie: Schulungsnachweise, Kompetenzmatrix, Zertifikate.",
  },
  {
    id: "ISO22301-7.3",
    domain: "7. Unterstützung",
    title: "Bewusstsein",
    erl: "Alle Mitarbeitenden müssen nachweislich über die BCM-Politik, ihre eigene Rolle im BCMS und die Konsequenzen einer Nichterfüllung informiert sein. Awareness-Programme, Schulungsunterlagen und Teilnahmenachweise müssen vorhanden sein.",
    q: "Sind sich die unter Aufsicht der Organisation tätigen Personen der BCM-Politik, ihres Beitrags zur Wirksamkeit des BCMS, der Folgen einer Nichterfüllung der Anforderungen sowie ihrer eigenen Rolle vor, während und nach Störungen bewusst?",
    hint: "Prüfen Sie: Awareness-Programme, Schulungsteilnahmequoten, Tests.",
  },
  {
    id: "ISO22301-7.4",
    domain: "7. Unterstützung",
    title: "Kommunikation",
    erl: "Ein Kommunikationsplan für das BCMS muss definieren: Über welche BCM-Themen kommuniziert wird, zu welchem Zeitpunkt, an welche Zielgruppen, über welche Kanäle und durch wen. Dies gilt für interne und externe Kommunikation.",
    q: "Ist festgelegt, worüber, wann, mit wem, wie und durch wen intern und extern zum BCMS kommuniziert wird?",
    hint: "Prüfen Sie: Kommunikationsplan, Eskalationswege.",
  },
  {
    id: "ISO22301-7.5.1",
    domain: "7. Unterstützung",
    title: "Dokumentierte Information – Allgemeines",
    erl: "Das BCMS muss alle von der Norm explizit geforderten dokumentierten Informationen enthalten sowie weitere Dokumente, die die Organisation für die wirksame Steuerung des BCMS als notwendig erachtet. Ein Dokumentenverzeichnis sollte vorliegen.",
    q: "Enthält das BCMS sowohl die von der Norm geforderte als auch die von der Organisation selbst als notwendig für die Wirksamkeit des BCMS bestimmte dokumentierte Information?",
    hint: "Prüfen Sie: Dokumentenlandkarte / -verzeichnis des BCMS.",
  },
  {
    id: "ISO22301-7.5.2",
    domain: "7. Unterstützung",
    title: "Erstellen und Aktualisieren",
    erl: "Alle BCMS-Dokumente müssen mit Titel, Datum, Version und Autor gekennzeichnet sein. Es muss ein definierter Genehmigungs- und Aktualisierungsprozess existieren. Das Format muss geeignet und das Medium zugänglich sein.",
    q: "Werden beim Erstellen und Aktualisieren dokumentierter Information angemessene Kennzeichnung/Beschreibung, Format/Medium sowie Überprüfung und Genehmigung sichergestellt?",
    hint: "Prüfen Sie: Dokumentvorlagen, Versionshistorie, Freigabeworkflows.",
  },
  {
    id: "ISO22301-7.5.3",
    domain: "7. Unterstützung",
    title: "Lenkung dokumentierter Information",
    erl: "Alle BCMS-Dokumente müssen zentral verwaltet, gegen unbefugten Zugriff geschützt und jederzeit auffindbar sein. Verteilung, Versionskontrolle, Archivierung und Verfügung müssen geregelt sein. Externe Dokumente müssen als solche gekennzeichnet sein.",
    q: "Wird die für das BCMS erforderliche dokumentierte Information gelenkt, sodass sie verfügbar, geeignet und angemessen geschützt ist (inkl. Verteilung, Zugriff, Ablage, Versionskontrolle, Aufbewahrung), und wird dokumentierte Information externer Herkunft angemessen gekennzeichnet und gelenkt?",
    hint: "Prüfen Sie: Dokumentenmanagementsystem, Zugriffsrechte, Archivierungsregeln.",
  },

  // 8. Betrieb
  {
    id: "ISO22301-8.1",
    domain: "8. Betrieb",
    title: "Betriebliche Planung und Steuerung",
    erl: "Die Organisation muss nachweisen, dass alle BCM-relevanten Prozesse geplant, gesteuert und überwacht werden. Prozesskriterien müssen definiert sein und dokumentierte Nachweise über die planmässige Durchführung müssen vorliegen. Ausgegliederte Prozesse und die Lieferkette müssen aktiv gesteuert werden.",
    q: "Werden die Prozesse zur Erfüllung der Anforderungen und zur Durchführung der unter 6.1 bestimmten Massnahmen geplant, umgesetzt und gesteuert (inkl. Kriterien, Steuerung, dokumentierter Information), werden geplante und unbeabsichtigte Änderungen überwacht/bewertet, und werden ausgegliederte Prozesse sowie die Lieferkette gesteuert?",
    hint: "Prüfen Sie: Prozesssteuerungsdokumente, Outsourcing-Verträge mit BC-Klauseln.",
  },
  {
    id: "ISO22301-8.2.1",
    domain: "8. Betrieb",
    title: "BIA und Risikobeurteilung – Allgemeines",
    erl: "Die Organisation muss systematische, dokumentierte Prozesse für die Business-Impact-Analyse und die Risikobeurteilung etabliert haben. Diese Prozesse müssen in regelmässigen Abständen und bei wesentlichen Änderungen überprüft und aktualisiert werden.",
    q: "Sind systematische Prozesse zur Business-Impact-Analyse und Risikobeurteilung umgesetzt, und werden diese in geplanten Abständen sowie bei signifikanten Änderungen überprüft?",
    hint: "Prüfen Sie: BIA-/Risikobeurteilungs-Methodik, Review-Historie.",
  },
  {
    id: "ISO22301-8.2.2.a",
    domain: "8. Betrieb",
    title: "Business-Impact-Analyse – Methodik, MTPD/RTO",
    erl: "Die BIA muss für alle kritischen Tätigkeiten die maximal zulässige Störungsdauer (MTPD) und den Wiederherstellungszeitpunkt (RTO) mit Mindestkapazität bestimmt haben. Die Einflussarten und -kriterien (finanziell, reputatorisch, regulatorisch etc.) müssen definiert und dokumentiert sein.",
    q: "Werden im Rahmen der BIA die relevanten Einflussarten und -kriterien festgelegt, Tätigkeiten ermittelt, die Produkte/Dienstleistungen unterstützen, sowie die maximal zulässige Störungsdauer (MTPD) und die Wiederherstellungszeitpunkte (RTO) für die Wiederaufnahme mit Mindestkapazität bestimmt?",
    hint: "Prüfen Sie: BIA-Berichte mit MTPD/RTO-Werten je Tätigkeit.",
  },
  {
    id: "ISO22301-8.2.2.b",
    domain: "8. Betrieb",
    title: "Business-Impact-Analyse – Betriebstätigkeiten hoher Priorität & Ressourcen",
    erl: "Auf Basis der BIA müssen Betriebstätigkeiten hoher Priorität identifiziert und deren Ressourcenbedarf (Personal, IT, Infrastruktur, Lieferanten) sowie alle Abhängigkeiten dokumentiert sein. Diese Liste bildet die Grundlage für die BC-Strategie.",
    q: "Werden auf Basis der BIA Betriebstätigkeiten hoher Priorität ermittelt, die dafür benötigten Ressourcen bestimmt und die Abhängigkeiten (inkl. Partner und Lieferanten) sowie Wechselbeziehungen dieser Tätigkeiten festgelegt?",
    hint: "Prüfen Sie: Liste der Betriebstätigkeiten hoher Priorität, Ressourcen- und Abhängigkeitsmatrix.",
  },
  {
    id: "ISO22301-8.2.3",
    domain: "8. Betrieb",
    title: "Risikobeurteilung",
    erl: "Für alle Betriebstätigkeiten hoher Priorität und deren Ressourcen muss eine Risikobeurteilung durchgeführt worden sein. Risiken müssen identifiziert, analysiert, bewertet und dokumentiert sein. Risiken mit Behandlungsbedarf müssen klar ausgewiesen werden.",
    q: "Werden die Risiken einer Störung der Betriebstätigkeiten hoher Priorität und der erforderlichen Ressourcen ermittelt, analysiert, bewertet, und wird bestimmt, welche Risiken eine Behandlung erfordern?",
    hint: "Prüfen Sie: Risikoregister mit Bezug zu Betriebstätigkeiten hoher Priorität, Verweis auf ISO 31000.",
  },
  {
    id: "ISO22301-8.3.1",
    domain: "8. Betrieb",
    title: "Strategien und Lösungen – Allgemeines",
    erl: "Die Organisation muss auf Basis der BIA- und Risikobeurteilungsergebnisse geeignete BC-Strategien entwickelt und ausgewählt haben. Die Strategien müssen Optionen vor, während und nach einer Störung abdecken und aus einer oder mehreren konkreten Lösungen bestehen.",
    q: "Wurden Strategien zur Aufrechterhaltung der Betriebsfähigkeit auf Grundlage der BIA- und Risikobeurteilungsergebnisse ermittelt und ausgewählt, die Optionen vor, während und nach einer Störung berücksichtigen und aus einer oder mehreren Lösungen bestehen?",
    hint: "Prüfen Sie: Strategiedokument mit Optionsbewertung.",
  },
  {
    id: "ISO22301-8.3.2",
    domain: "8. Betrieb",
    title: "Identifizierung der Strategien und Lösungen",
    erl: "Bei der Identifizierung von BC-Strategien und -Lösungen muss systematisch bewertet werden, inwieweit diese Tätigkeiten hoher Priorität fortführen/wiederherstellen, schützen, die Störungswahrscheinlichkeit/-dauer reduzieren, die Auswirkung begrenzen und Ressourcen sicherstellen.",
    q: "Erfolgt die Identifizierung von Strategien/Lösungen anhand des Umfangs, in dem sie Tätigkeiten hoher Priorität fortführen/wiederherstellen, diese schützen, die Wahrscheinlichkeit und Dauer einer Störung reduzieren, die Auswirkung begrenzen und die Verfügbarkeit von Ressourcen sicherstellen?",
    hint: "Prüfen Sie: Bewertungsmatrix der Lösungsoptionen.",
  },
  {
    id: "ISO22301-8.3.3",
    domain: "8. Betrieb",
    title: "Auswahl der Strategien und Lösungen",
    erl: "Die Auswahl der BC-Strategien muss nachvollziehbar begründet sein, unter Abwägung von Risikotoleranz, Kosten und Nutzen. Entscheidungsgrundlagen und Optionenvergleiche müssen dokumentiert vorliegen.",
    q: "Erfolgt die Auswahl der Strategien/Lösungen unter Berücksichtigung der Anforderungen, des akzeptablen Risikoumfangs/-art sowie der damit verbundenen Kosten und Nutzen?",
    hint: "Prüfen Sie: Entscheidungsvorlagen, Kosten-Nutzen-Analysen.",
  },
  {
    id: "ISO22301-8.3.4",
    domain: "8. Betrieb",
    title: "Ressourcenbedarf für Lösungen",
    erl: "Für jede gewählte BC-Lösung muss der vollständige Ressourcenbedarf bestimmt sein: Personal, Daten/Informationen, Infrastruktur, Ausrüstung, ICT-Systeme, Transport/Logistik, Finanzen sowie Partner und Lieferanten.",
    q: "Wurde der Ressourcenbedarf zur Umsetzung der gewählten Lösungen bestimmt (Personen, Informationen/Daten, materielle Infrastruktur, Ausrüstung/Verbrauchsmittel, ICT-Systeme, Transport/Logistik, Finanzen, Partner/Lieferanten)?",
    hint: "Prüfen Sie: Ressourcenplanung je Lösung.",
  },
  {
    id: "ISO22301-8.3.5",
    domain: "8. Betrieb",
    title: "Umsetzung von Lösungen",
    erl: "Alle gewählten BC-Lösungen müssen tatsächlich umgesetzt und so aufrechterhalten sein, dass sie im Bedarfsfall aktiviert werden können. Nachweise der Umsetzung (z.B. Verträge, Systemkonfigurationen, Alternativstandorte, Bereitschaftsnachweise) müssen vorliegen.",
    q: "Werden die ausgewählten Lösungen zur Aufrechterhaltung der Betriebsfähigkeit umgesetzt und so aufrechterhalten, dass sie bei Bedarf aktiviert werden können?",
    hint: "Prüfen Sie: Implementierungsnachweise, Aktivierungstests.",
  },
  {
    id: "ISO22301-8.4.1",
    domain: "8. Betrieb",
    title: "Pläne und Verfahren – Allgemeines",
    erl: "Die Organisation muss eine Reaktionsstruktur und dokumentierte BC-Pläne und -Verfahren haben, die bei Störungen aktiviert werden. Die Verfahren müssen präzise Schritte für den Ernstfall definieren, flexibel auf veränderliche Lagen reagieren können und klare Rollen und Verantwortlichkeiten enthalten.",
    q: "Ist eine Reaktionsstruktur umgesetzt, die zeitnahe Warnung und Kommunikation ermöglicht, und stehen Pläne/Verfahren zur Steuerung der Organisation während einer Störung bereit, die genau festgelegt, flexibel, auf Auswirkungen fokussiert sowie mit Rollen/Verantwortlichkeiten versehen sind?",
    hint: "Prüfen Sie: Übersicht der BC-Pläne und Reaktionsverfahren.",
  },
  {
    id: "ISO22301-8.4.2.a",
    domain: "8. Betrieb",
    title: "Reaktionsstruktur – Teams",
    erl: "Es müssen ein oder mehrere Reaktionsteams mit definierten Rollen, Verantwortlichkeiten, Befugnissen und Stellvertretungen eingerichtet sein. Jedes Team muss über dokumentierte Verfahren für Aktivierung, Betrieb, Koordination und Kommunikation einer Reaktion verfügen.",
    q: "Sind eine Struktur und ein oder mehrere Teams für die Reaktion auf Störungen umgesetzt, sind Rollen/Verantwortlichkeiten jedes Teams und die Beziehungen zwischen den Teams klar beschrieben, und ist jedes Team mit kompetentem Personal und Stellvertretern sowie dokumentierten Verfahren ausgestattet?",
    hint: "Prüfen Sie: Teamstruktur, Stellvertreterregelungen, Verfahrensdokumente.",
  },
  {
    id: "ISO22301-8.4.2.b",
    domain: "8. Betrieb",
    title: "Reaktionsstruktur – Fähigkeiten der Teams",
    erl: "Die Reaktionsteams müssen zusammen in der Lage sein, den gesamten Reaktionszyklus zu bewältigen: Lagebeurteilung, Auslösung der Reaktion anhand von Schwellenwerten, Priorisierung (Menschenleben zuerst), Überwachung der Auswirkungen, Aktivierung von BC-Lösungen und Kommunikation mit allen relevanten Parteien.",
    q: "Sind die Teams zusammen in der Lage, Beschaffenheit/Ausmass einer Störung zu beurteilen, anhand von Schwellenwerten eine formale Reaktion auszulösen, Massnahmen zu planen und zu priorisieren (Menschenleben zuerst), die Auswirkungen zu überwachen, Lösungen zu aktivieren und mit relevanten Parteien, Behörden und Medien zu kommunizieren?",
    hint: "Prüfen Sie: Eskalationsschwellen, Übungsberichte zur Teamreaktion.",
  },
  {
    id: "ISO22301-8.4.3.a",
    domain: "8. Betrieb",
    title: "Warnung und Kommunikation – Verfahren",
    erl: "Dokumentierte Kommunikationsverfahren müssen regeln: interne und externe Kommunikation (was, wann, mit wem, wie), Empfang und Beantwortung von Mitteilungen interessierter Parteien, Sicherstellung der Kommunikationsmittel, Kommunikation mit Notfallhelfern, Medienmanagement sowie lückenlose Dokumentation der Störungsdetails.",
    q: "Sind Verfahren dokumentiert und aufrechterhalten für die interne/externe Kommunikation (was, wann, mit wem, wie), für den Empfang und die Beantwortung von Mitteilungen interessierter Parteien, für die Sicherstellung verfügbarer Kommunikationsmittel während einer Störung, für die Kommunikation mit Notfallhelfern, für Medienanfragen sowie für die Aufzeichnung von Störungsdetails, Massnahmen und Entscheidungen?",
    hint: "Prüfen Sie: Kommunikationsverfahren, Medien-/Krisenkommunikationsplan.",
  },
  {
    id: "ISO22301-8.4.3.b",
    domain: "8. Betrieb",
    title: "Warnung und Kommunikation – Ergänzende Massnahmen & Übung",
    erl: "Warnmeldungen an potenziell betroffene Parteien und die Koordination mit anderen reagierenden Organisationen müssen geregelt sein. Die Kommunikationsverfahren müssen regelmässig im Rahmen des Übungsprogramms geübt und die Ergebnisse dokumentiert werden.",
    q: "Werden, soweit zutreffend, Warnmeldungen an potenziell betroffene interessierte Parteien herausgegeben, wird die Koordination zwischen mehreren reagierenden Organisationen sichergestellt, und werden die Warn- und Kommunikationsverfahren im Rahmen des Übungsprogramms durchgeführt?",
    hint: "Prüfen Sie: Übungsberichte zu Warn-/Kommunikationsverfahren.",
  },
  {
    id: "ISO22301-8.4.4.a",
    domain: "8. Betrieb",
    title: "BC-Pläne – Gesamtinhalt",
    erl: "Die Gesamtheit der BC-Pläne muss alle Normanforderungen abdecken: Massnahmen zur Fortsetzung/Wiederherstellung, Überwachung der Störungsreaktion, Aktivierungsschwellen und -prozesse, Verfahren zur Belieferung mit vereinbarter Kapazität sowie Massnahmen zum Schutz von Personen, zur Schadensbegrenzung und zum Umweltschutz.",
    q: "Enthalten die Pläne insgesamt Massnahmen der Teams zur Fortsetzung/Wiederherstellung von Tätigkeiten hoher Priorität und zur Überwachung der Störung, Verweis auf Schwellenwerte/Aktivierungsprozess, Verfahren zur Belieferung mit vereinbarter Kapazität sowie Massnahmen zur Steuerung unmittelbarer Auswirkungen (Wohlergehen von Personen, Vermeidung weiterer Schäden, Umweltschutz)?",
    hint: "Prüfen Sie: BC-Pläne auf Vollständigkeit gemäss 8.4.4.2.",
  },
  {
    id: "ISO22301-8.4.4.b",
    domain: "8. Betrieb",
    title: "BC-Pläne – Einzelplan-Inhalt",
    erl: "Jeder einzelne BC-Plan muss folgende Elemente enthalten: Zweck/Scope/Ziele, Rollen und Verantwortlichkeiten des umsetzenden Teams, Aktivierungskriterien und -prozess, konkrete Massnahmen, interne/externe Wechselbeziehungen, Ressourcenanforderungen, Berichtspflichten und einen Beendigungsprozess. Der Plan muss am Einsatzort und zum Einsatzzeitpunkt verfügbar sein.",
    q: "Enthält jeder einzelne Plan Zweck/Anwendungsbereich/Zielsetzungen, Rollen/Verantwortlichkeiten des umsetzenden Teams, Massnahmen zur Lösungsumsetzung, Aktivierungsinformationen, interne/externe Wechselbeziehungen, Ressourcenanforderungen, Berichterstattungsanforderungen und einen Beendigungsprozess, und ist jeder Plan am benötigten Ort/Zeitpunkt verfügbar?",
    hint: "Prüfen Sie: Stichprobe einzelner BC-Pläne gegen die Checkliste 8.4.4.3.",
  },
  {
    id: "ISO22301-8.4.5",
    domain: "8. Betrieb",
    title: "Wiederherstellung",
    erl: "Dokumentierte Prozesse für die geordnete Rückkehr vom Notbetrieb zum Normalbetrieb müssen vorhanden sein. Diese müssen festlegen, wann und wie die Übergangsphase beendet wird, wie normale Prozesszustände wiederhergestellt werden und wer dafür verantwortlich ist.",
    q: "Verfügt die Organisation über dokumentierte Prozesse zur Wiederherstellung und Rückkehr der Geschäftstätigkeiten aus den vorübergehend eingeführten Massnahmen nach und während einer Störung?",
    hint: "Prüfen Sie: Wiederherstellungs-/Rückkehrverfahren.",
  },
  {
    id: "ISO22301-8.5",
    domain: "8. Betrieb",
    title: "Übungsprogramm",
    erl: "Ein systematisches Übungsprogramm muss existieren und durchgeführt werden. Es muss Szenarien, Ziele, Häufigkeit, Verantwortlichkeiten und ein Berichtsformat definieren. Nach jeder Übung müssen Ergebnisse, Empfehlungen und Massnahmen dokumentiert und konsequent umgesetzt werden.",
    q: "Wird ein Übungs- und Überprüfungsprogramm umgesetzt, das mit den BCM-Zielen abgestimmte, sorgfältig geplante Szenarien nutzt, Teamwork/Kompetenz/Vertrauen entwickelt, die Gesamtheit der Strategien/Lösungen validiert, formalisierte Berichte erzeugt, im Kontext der fortlaufenden Verbesserung überprüft und in geplanten Abständen/bei signifikanten Änderungen durchgeführt wird, und reagiert die Organisation auf die Ergebnisse mit Änderungen/Verbesserungen?",
    hint: "Prüfen Sie: Übungsplan, Übungsberichte, Massnahmen aus Lessons Learned.",
  },
  {
    id: "ISO22301-8.6",
    domain: "8. Betrieb",
    title: "Bewertung der Dokumentation und Fähigkeiten",
    erl: "Die Organisation muss systematisch und periodisch die Eignung und Wirksamkeit aller BCM-Elemente bewerten: BIA, Risikobeurteilung, Strategien, Pläne, Verfahren sowie die BCM-Fähigkeiten von Partnern und Lieferanten. Compliance mit gesetzlichen Vorgaben und eigener Politik muss geprüft und Dokumentation zeitnah aktualisiert werden.",
    q: "Werden Eignung, Angemessenheit und Wirksamkeit von BIA, Risikobeurteilung, Strategien, Lösungen, Plänen und Verfahren bewertet (u.a. durch Überprüfungen, Analysen, Übungen, Prüfungen, Berichte nach Zwischenfällen), werden auch die Fähigkeiten relevanter Partner/Lieferanten bewertet, wird Compliance mit rechtlichen/behördlichen Vorgaben und eigener Politik/Zielen geprüft, und werden Dokumentation/Verfahren zeitnah aktualisiert?",
    hint: "Prüfen Sie: Bewertungsberichte, Aktualisierungsnachweise.",
  },

  // 9. Bewertung der Leistung
  {
    id: "ISO22301-9.1",
    domain: "9. Bewertung der Leistung",
    title: "Überwachung, Messung, Analyse und Bewertung",
    erl: "Die Organisation muss definiert haben, was gemessen wird (z.B. RTO-Einhaltung, Übungsfrequenz, Dokumentenaktualität), welche Methoden verwendet werden, wer misst und wann, und wer die Ergebnisse analysiert. Messnachweise müssen dokumentiert aufbewahrt werden.",
    q: "Ist bestimmt, was überwacht/gemessen wird, welche Methoden angewendet werden, wann und von wem Überwachung/Messung sowie Analyse/Bewertung erfolgen, wird dies dokumentiert, und wird die Leistung und Wirksamkeit des BCMS bewertet?",
    hint: "Prüfen Sie: KPI-Katalog, Messberichte.",
  },
  {
    id: "ISO22301-9.2.1",
    domain: "9. Bewertung der Leistung",
    title: "Internes Audit – Allgemeines",
    erl: "Die Organisation muss interne Audits in definierten Abständen durchführen, die prüfen, ob das BCMS die eigenen Anforderungen und die Normanforderungen erfüllt und wirksam aufrechterhalten wird. Audit-Berichte und Massnahmenverfolgung müssen vorliegen.",
    q: "Werden in geplanten Abständen interne Audits durchgeführt, um festzustellen, ob das BCMS die eigenen Anforderungen sowie die Anforderungen dieser Norm erfüllt und wirksam umgesetzt/aufrechterhalten wird?",
    hint: "Prüfen Sie: Auditberichte, Auditzyklus.",
  },
  {
    id: "ISO22301-9.2.2",
    domain: "9. Bewertung der Leistung",
    title: "Auditprogramm(e)",
    erl: "Ein dokumentiertes Auditprogramm muss existieren, das Häufigkeit, Methoden, Verantwortlichkeiten, Auditkriterien und Berichterstattung festlegt. Auditoren müssen objektiv und unabhängig von den auditierten Bereichen sein. Nichtkonformitäten müssen verfolgt und Korrekturmassnahmen verifiziert werden.",
    q: "Sind ein oder mehrere Auditprogramme geplant/aufgebaut (inkl. Häufigkeit, Methoden, Verantwortlichkeiten, Berichterstattung), sind Auditkriterien/-umfang je Audit festgelegt, wird die Objektivität/Unparteilichkeit der Auditoren sichergestellt, werden Ergebnisse an die zuständige Leitung berichtet, wird dokumentierte Information aufbewahrt, und werden Korrekturmassnahmen samt Verifizierung sichergestellt?",
    hint: "Prüfen Sie: Auditprogramm, Auditorenqualifikation, Nachweis der Massnahmenverfolgung.",
  },
  {
    id: "ISO22301-9.3.1",
    domain: "9. Bewertung der Leistung",
    title: "Managementbewertung – Allgemeines",
    erl: "Die oberste Leitung muss das BCMS in definierten Abständen (mindestens jährlich empfohlen) formal bewerten. Terminplanung und Protokolle dieser Bewertungen mit Beschlüssen und Massnahmen müssen vorliegen.",
    q: "Bewertet die oberste Leitung das BCMS in geplanten Abständen, um dessen fortdauernde Eignung, Angemessenheit und Wirksamkeit sicherzustellen?",
    hint: "Prüfen Sie: Termine/Protokolle der Managementbewertung.",
  },
  {
    id: "ISO22301-9.3.2",
    domain: "9. Bewertung der Leistung",
    title: "Eingaben für die Managementbewertung",
    erl: "Die Managementbewertung muss alle von der Norm geforderten Eingaben behandeln (a bis k gemäss 9.3.2): Status früherer Massnahmen, Kontextveränderungen, BCMS-Leistungsdaten (Nichtkonformitäten, Messergebnisse, Auditergebnisse), Stakeholder-Rückmeldungen, Änderungsbedarf, Verbesserungsmöglichkeiten, BIA/Risiko-Informationen, Ergebnisse aus 8.6 sowie Erfahrungen aus Störungen.",
    q: "Behandelt die Managementbewertung u.a. den Status früherer Massnahmen, Veränderungen bei externen/internen Themen, BCMS-Leistungsinformationen (Nichtkonformitäten, Mess-/Auditergebnisse), Rückmeldungen interessierter Parteien, Änderungsbedarf am BCMS, Verbesserungsmöglichkeiten, Informationen aus BIA/Risikobeurteilung, Ergebnisse aus 8.6 sowie Erfahrungen aus Beinaheunfällen/Störungen?",
    hint: "Prüfen Sie: Vollständige Traktandenliste/Unterlagen der Managementbewertung gegen 9.3.2 a)–k).",
  },
  {
    id: "ISO22301-9.3.3",
    domain: "9. Bewertung der Leistung",
    title: "Ergebnisse der Managementbewertung",
    erl: "Die Managementbewertung muss zu konkreten Entscheidungen und Massnahmen führen: Verbesserungen, BCMS-Anpassungen, Ressourcenzuteilung. Ergebnisse und Beschlüsse müssen dokumentiert, an relevante Parteien kommuniziert und konsequent verfolgt werden.",
    q: "Enthalten die Ergebnisse der Managementbewertung Entscheidungen zu fortlaufender Verbesserung und Änderungsbedarf am BCMS (inkl. BIA/Risikobeurteilung/Strategien/Lösungen/Pläne, Verfahren/Kontrollen, Wirksamkeitsmessung), wird dokumentierte Information aufbewahrt, und werden Ergebnisse den relevanten interessierten Parteien mitgeteilt und entsprechende Massnahmen ergriffen?",
    hint: "Prüfen Sie: Protokoll/Beschlüsse der Managementbewertung, Nachweis der Kommunikation.",
  },

  // 10. Verbesserung
  {
    id: "ISO22301-10.1",
    domain: "10. Verbesserung",
    title: "Nichtkonformität und Korrekturmassnahmen",
    erl: "Bei jeder festgestellten Nichtkonformität muss die Organisation reagieren, Ursachen analysieren (Rootcause), Korrekturmassnahmen einleiten und deren Wirksamkeit prüfen. Ein CAPA-Register (Corrective and Preventive Actions) muss geführt werden. Alle Nichtkonformitäten, Massnahmen und Ergebnisse müssen dokumentiert sein.",
    q: "Werden bei Auftreten einer Nichtkonformität angemessene Sofortmassnahmen ergriffen, die Ursache bewertet und beseitigt (inkl. Prüfung vergleichbarer Nichtkonformitäten), die Wirksamkeit der Korrekturmassnahme überprüft, das BCMS bei Bedarf angepasst, und wird dokumentierte Information über Art der Nichtkonformität, getroffene Massnahmen und Ergebnisse aufbewahrt?",
    hint: "Prüfen Sie: Nichtkonformitäten-/CAPA-Register.",
  },
  {
    id: "ISO22301-10.2",
    domain: "10. Verbesserung",
    title: "Fortlaufende Verbesserung",
    erl: "Die Organisation muss einen systematischen Ansatz zur kontinuierlichen Verbesserung des BCMS verfolgen. Verbesserungen müssen auf Basis von Messdaten, Auditresultaten, Managementbewertungen und Lessons Learned aus Übungen/Störungen identifiziert, priorisiert und umgesetzt werden. Ein Verbesserungsregister sollte geführt werden.",
    q: "Verbessert die Organisation Eignung, Angemessenheit und Wirksamkeit des BCMS fortlaufend auf Grundlage qualitativer und quantitativer Massnahmen, unter Berücksichtigung der Ergebnisse aus Analyse/Bewertung und Managementbewertung?",
    hint: "Prüfen Sie: Verbesserungsregister, Trendanalysen über mehrere Zyklen.",
  },
];
