// ISO 22301:2019 (DIN EN ISO 22301:2020-06) — Anforderungskatalog
// Struktur pro Eintrag: { id, domain, title, q, hint }

export const DOMAINS = [
  "4. Kontext der Organisation",
  "5. Führung",
  "6. Planung",
  "7. Unterstützung",
  "8. Betrieb",
  "9. Bewertung der Leistung",
  "10. Verbesserung",
];

// Akzentfarbe je Bereich
export const DC = {
  "4. Kontext der Organisation": "#5B2D8E", // lila
  "5. Führung": "#0B3B5C", // dunkelblau
  "6. Planung": "#00C9A7", // türkis
  "7. Unterstützung": "#8DB33A", // olivgrün
  "8. Betrieb": "#47B8D4", // hellblau
  "9. Bewertung der Leistung": "#E8660A", // orange
  "10. Verbesserung": "#C0392B", // ziegelrot
};

// Helle Hintergrundvariante je Bereich
export const DC_BG = {
  "4. Kontext der Organisation": "#EDE0F5",
  "5. Führung": "#E0EAF2",
  "6. Planung": "#D6F5EE",
  "7. Unterstützung": "#EDF3D6",
  "8. Betrieb": "#D6F0F7",
  "9. Bewertung der Leistung": "#FBE7D6",
  "10. Verbesserung": "#F8DDD9",
};

export const CONTROLS = [
  // ── 4. Kontext der Organisation ──────────────────────────────────────────
  {
    id: "ISO22301-4.1",
    domain: "4. Kontext der Organisation",
    title: "Externe und interne Themen",
    erl: "Die Organisation muss nachweisen, dass sie systematisch analysiert hat, welche externen Faktoren (wirtschaftliches Umfeld, regulatorische Anforderungen, Marktbedingungen, gesellschaftliche Entwicklungen) und internen Faktoren (Organisationsstruktur, Ressourcen, Kultur, Prozesse) das BCMS beeinflussen. Diese Analyse muss dokumentiert und aktuell gehalten werden.",
    req: "Gefordert wird ein dokumentiertes Ergebnis einer Kontextanalyse (z.B. SWOT, PESTEL oder gleichwertige Methode), das externe Einflussfaktoren (Markt, Regulierung, Technologie, Wettbewerb) und interne Einflussfaktoren (Struktur, Ressourcen, Prozesse, Kultur) aufführt und bewertet, wie sie die BCMS-Ziele beeinflussen. Eine definierte Aktualisierungsfrequenz muss festgelegt sein.",
    q: "Hat die Organisation externe und interne Themen bestimmt, die für den Zweck des BCMS relevant sind und sich auf die Erreichung der beabsichtigten Ergebnisse auswirken?",
    hint: "Prüfen Sie: Kontextanalyse, SWOT/PESTEL, Geschäftsstrategie, Protokolle der Leitungsbewertung.",
  },
  {
    id: "ISO22301-4.2.1",
    domain: "4. Kontext der Organisation",
    title: "Interessierte Parteien",
    erl: "Die Organisation muss eine vollständige Liste der für das BCMS relevanten Stakeholder erstellen und deren jeweilige Anforderungen und Erwartungen an die Aufrechterhaltung der Betriebsfähigkeit bestimmen und dokumentieren. Dazu gehören u.a. Kunden, Lieferanten, Behörden, Eigentümer und Mitarbeitende.",
    req: "Gefordert wird eine aktuelle, vollständige Stakeholder-Liste. Für jeden relevanten Stakeholder müssen dessen spezifische Anforderungen und Erwartungen an die Betriebskontinuität dokumentiert sein. Die Stakeholder-Analyse muss regelmässig überprüft werden.",
    q: "Wurden die für das BCMS relevanten interessierten Parteien sowie deren relevante Anforderungen identifiziert und dokumentiert?",
    hint: "Prüfen Sie: Stakeholder-Liste, Verträge, Erwartungsmatrix.",
  },
  {
    id: "ISO22301-4.2.2",
    domain: "4. Kontext der Organisation",
    title: "Rechtliche und behördliche Anforderungen",
    erl: "Die Organisation muss einen dokumentierten Prozess etabliert haben, um alle geltenden rechtlichen, regulatorischen und behördlichen Anforderungen zu ermitteln, zu bewerten und in das BCMS zu integrieren. Das Rechtsregister muss aktuell gehalten und bei der BCMS-Umsetzung berücksichtigt werden.",
    req: "Gefordert wird ein Rechtsregister oder eine Compliance-Liste mit allen BCM-relevanten gesetzlichen, regulatorischen und behördlichen Anforderungen. Ein Verantwortlicher für die Pflege dieses Registers muss benannt und ein definierter Aktualisierungsprozess muss dokumentiert sein.",
    q: "Existiert ein Prozess zur Ermittlung, zum Zugriff auf und zur Bewertung geltender rechtlicher, behördlicher und sonstiger Anforderungen, und werden diese dokumentiert, aktuell gehalten und im BCMS berücksichtigt?",
    hint: "Prüfen Sie: Rechtsregister, Compliance-Liste, Nachweis der Aktualisierung.",
  },
  {
    id: "ISO22301-4.3.1",
    domain: "4. Kontext der Organisation",
    title: "Grundlagen für den Anwendungsbereich",
    erl: "Beim Festlegen des BCMS-Anwendungsbereichs muss die Organisation nachweisen, dass sie die Kontextanalyse (4.1), die Stakeholder-Anforderungen (4.2) sowie den eigenen Auftrag, Ziele und Verpflichtungen berücksichtigt hat. Die Herleitung des Scope muss transparent und nachvollziehbar dokumentiert sein.",
    req: "Gefordert wird ein Scope-Dokument, das nachvollziehbar darlegt, wie die Ergebnisse der Kontextanalyse (4.1), der Stakeholder-Anforderungen (4.2) sowie der eigene Auftrag bei der Festlegung des Anwendungsbereichs berücksichtigt wurden. Die Herleitung muss für einen externen Prüfer nachvollziehbar sein.",
    q: "Wurden bei der Festlegung des Anwendungsbereichs des BCMS die externen/internen Themen (4.1), die Anforderungen interessierter Parteien (4.2) sowie Auftrag, Ziele und Verpflichtungen der Organisation berücksichtigt?",
    hint: "Prüfen Sie: Scope-Dokument mit Begründung der Herleitung.",
  },
  {
    id: "ISO22301-4.3.2",
    domain: "4. Kontext der Organisation",
    title: "Anwendungsbereich des BCMS",
    erl: "Der Anwendungsbereich muss klar definieren, welche Organisationsteile (Standorte, Geschäftsbereiche), Produkte und Dienstleistungen eingeschlossen sind. Ausschlüsse müssen begründet sein und dürfen die BCM-Fähigkeit nicht untergraben. Das Scope-Dokument muss als dokumentierte Information vorliegen.",
    req: "Gefordert wird ein Scope-Statement, das konkret benennt: welche Standorte, Organisationseinheiten, Produkte und Dienstleistungen eingeschlossen sind. Ausschlüsse müssen namentlich genannt und begründet sein. Das Dokument muss versionskontrolliert vorliegen und regelmässig überprüft werden.",
    q: "Sind die einbezogenen Organisationsteile (Standorte, Grösse, Art, Komplexität) und Produkte/Dienstleistungen festgelegt, sind Ausschlüsse dokumentiert und begründet, und liegt der Anwendungsbereich als dokumentierte Information vor?",
    hint: "Prüfen Sie: Scope-Statement, Ausschlussliste mit Begründung.",
  },
  {
    id: "ISO22301-4.4",
    domain: "4. Kontext der Organisation",
    title: "BCMS als Ganzes",
    erl: "Die Organisation muss nachweisen, dass ein BCMS nach den Normanforderungen aufgebaut und aktiv in Betrieb ist. Dies umfasst alle geforderten Prozesse, deren Wechselwirkungen und die relevanten dokumentierten Informationen.",
    req: "Gefordert wird ein BCMS-Handbuch oder eine gleichwertige Übersicht, die zeigt, dass alle Normanforderungen (Kap. 4–10) durch definierte Prozesse, Verfahren und Dokumente abgedeckt sind. Die Wechselwirkungen der Prozesse müssen beschrieben sein.",
    q: "Wurde ein BCMS gemäss den Anforderungen der Norm aufgebaut, umgesetzt, aufrechterhalten und wird es fortlaufend verbessert, einschliesslich der benötigten Prozesse und ihrer Wechselwirkungen?",
    hint: "Prüfen Sie: Prozesslandkarte / BCMS-Handbuch.",
  },

  // ── 5. Führung ───────────────────────────────────────────────────────────
  {
    id: "ISO22301-5.1.a",
    domain: "5. Führung",
    title: "Führung und Verpflichtung – Ausrichtung & Integration",
    erl: "Die oberste Leitung muss aktiv und sichtbar die BCM-Politik und die BCM-Ziele vertreten und sicherstellen, dass diese mit der Unternehmensstrategie in Einklang stehen. BCM-Anforderungen müssen in alle relevanten Geschäftsprozesse integriert sein.",
    req: "Gefordert werden Sitzungsprotokolle der Geschäftsleitung, die BCM als Traktandum ausweisen. BCM-Ziele müssen in strategischen Planungsdokumenten verankert sein. Die BCM-Anforderungen müssen in bestehende Geschäftsprozesse (z.B. Einkauf, IT, HR) integriert und nicht als isoliertes Projekt geführt werden.",
    q: "Stellt die oberste Leitung sicher, dass Politik und Ziele zur Aufrechterhaltung der Betriebsfähigkeit festgelegt sind, mit der strategischen Ausrichtung übereinstimmen und in die Geschäftsprozesse integriert sind?",
    hint: "Prüfen Sie: Strategiepapiere, Sitzungsprotokolle der Geschäftsleitung.",
  },
  {
    id: "ISO22301-5.1.b",
    domain: "5. Führung",
    title: "Führung und Verpflichtung – Ressourcen & Förderung",
    erl: "Die oberste Leitung muss nachweislich die notwendigen Ressourcen (Personal, Budget, Zeit) für das BCMS bereitstellen, die Bedeutung von BCM aktiv kommunizieren, fortlaufende Verbesserung fördern und andere Führungskräfte in ihrer BCM-Verantwortung unterstützen.",
    req: "Gefordert werden genehmigte Budgets für BCM-Aktivitäten (Übungen, Schulungen, Tools, Ausrüstung) sowie Nachweise der aktiven Kommunikation der Geschäftsleitung zu BCM (z.B. Rundschreiben, Townhall-Protokolle). Die Unterstützung anderer Führungskräfte in deren BCM-Rolle muss nachweisbar sein.",
    q: "Stellt die oberste Leitung sicher, dass die für das BCMS erforderlichen Ressourcen verfügbar sind, vermittelt sie die Bedeutung des BCM, fördert sie fortlaufende Verbesserung und unterstützt sie andere Führungskräfte in deren Führungsrolle?",
    hint: "Prüfen Sie: Budgetfreigaben, interne Kommunikation, Verantwortlichkeitsmatrix.",
  },
  {
    id: "ISO22301-5.2.1",
    domain: "5. Führung",
    title: "Festlegung der BCM-Politik",
    erl: "Eine formale, von der obersten Leitung genehmigte BCM-Politik muss vorliegen. Sie muss den Zweck und Rahmen des BCMS beschreiben, messbare Ziele ermöglichen, die Einhaltung relevanter Anforderungen zusichern und die Verpflichtung zur kontinuierlichen Verbesserung enthalten.",
    req: "Gefordert wird ein formales BCM-Politikdokument, das von der obersten Leitung unterzeichnet und datiert ist und mindestens folgende Elemente enthält: Verpflichtungserklärung, Geltungsbereich, Ziele oder Zielrahmen, Verantwortlichkeiten auf höchster Ebene sowie Verpflichtung zur Verbesserung.",
    q: "Ist eine Politik zur Aufrechterhaltung der Betriebsfähigkeit festgelegt, die für den Zweck der Organisation angemessen ist, einen Rahmen für Ziele bietet und Verpflichtungen zur Erfüllung anwendbarer Anforderungen sowie zur fortlaufenden Verbesserung enthält?",
    hint: "Prüfen Sie: BCM-Politikdokument, Freigabevermerk der Geschäftsleitung.",
  },
  {
    id: "ISO22301-5.2.2",
    domain: "5. Führung",
    title: "Bekanntmachung der BCM-Politik",
    erl: "Die BCM-Politik muss allen Mitarbeitenden bekannt gemacht worden sein und für relevante interessierte Parteien zugänglich sein. Ein Nachweis der Kommunikation muss vorliegen.",
    req: "Gefordert wird ein Nachweis der Bekanntmachung der BCM-Politik (z.B. Intranet-Veröffentlichung, Schulungsunterlagen, Verteilerlisten). Für externe Stakeholder (z.B. Kunden, Behörden) muss ein Verfahren zur Bereitstellung auf Anfrage existieren.",
    q: "Ist die Politik als dokumentierte Information verfügbar, innerhalb der Organisation bekanntgemacht und – soweit angemessen – interessierten Parteien zugänglich?",
    hint: "Prüfen Sie: Intranet, Schulungsunterlagen, Verteilerliste.",
  },
  {
    id: "ISO22301-5.3",
    domain: "5. Führung",
    title: "Rollen, Verantwortlichkeiten, Befugnisse",
    erl: "Alle BCM-relevanten Rollen müssen mit klaren Verantwortlichkeiten und Befugnissen definiert und besetzt sein. Dies schliesst mindestens die Rolle des BCM-Verantwortlichen und die Berichterstattung an die oberste Leitung ein.",
    req: "Gefordert werden Rollenbeschreibungen für alle BCM-relevanten Funktionen (mindestens: BCM-Verantwortlicher, Reaktionsteam-Leiter, Stellvertreter) mit klaren Verantwortlichkeiten und Befugnissen. Diese müssen den betroffenen Personen schriftlich kommuniziert worden sein. Eine RACI-Matrix oder vergleichbares Dokument ist empfohlen.",
    q: "Sind Verantwortlichkeiten und Befugnisse für relevante BCM-Rollen zugewiesen, kommuniziert, und schliesst dies die Sicherstellung der BCMS-Konformität sowie die Berichterstattung an die oberste Leitung ein?",
    hint: "Prüfen Sie: Organigramm, Rollenbeschreibungen, RACI-Matrix.",
  },

  // ── 6. Planung ───────────────────────────────────────────────────────────
  {
    id: "ISO22301-6.1.1",
    domain: "6. Planung",
    title: "Bestimmung von Risiken und Chancen",
    erl: "Im Rahmen der BCMS-Planung müssen Risiken und Chancen identifiziert werden, die die Wirksamkeit des Managementsystems selbst (nicht Betriebsstörungen) beeinflussen.",
    req: "Gefordert wird ein Risikoregister auf BCMS-Ebene (nicht zu verwechseln mit dem operativen Risikoregister aus 8.2.3), das Risiken und Chancen für die Wirksamkeit des Managementsystems selbst aufführt – z.B. fehlende Führungsunterstützung, mangelnde Ressourcen, veraltete Dokumente.",
    q: "Wurden bei der Planung des BCMS die Themen aus 4.1 und Anforderungen aus 4.2 berücksichtigt, um Risiken und Chancen zu bestimmen?",
    hint: "Prüfen Sie: Risiko- und Chancenregister auf Managementsystemebene.",
  },
  {
    id: "ISO22301-6.1.2",
    domain: "6. Planung",
    title: "Umgang mit Risiken und Chancen",
    erl: "Für die identifizierten Risiken und Chancen müssen konkrete Massnahmen geplant sein, inklusive deren Integration in die BCMS-Prozesse und einer Methode zur Bewertung ihrer Wirksamkeit.",
    req: "Gefordert wird ein Massnahmenplan, der für jeden Eintrag im BCMS-Risikoregister eine zugewiesene Massnahme mit Verantwortlichem und Termin enthält. Die Wirksamkeit umgesetzter Massnahmen muss nachweislich überprüft werden.",
    q: "Sind Massnahmen zum Umgang mit den identifizierten Risiken und Chancen geplant, inklusive deren Integration in BCMS-Prozesse und Bewertung ihrer Wirksamkeit?",
    hint: "Prüfen Sie: Massnahmenpläne, Verknüpfung mit 8.1 und 9.1.",
  },
  {
    id: "ISO22301-6.2.1",
    domain: "6. Planung",
    title: "Ziele zur Aufrechterhaltung der Betriebsfähigkeit",
    erl: "Die Organisation muss messbare BCM-Ziele für relevante Funktionen und Ebenen festgelegt haben, die mit der BCM-Politik übereinstimmen, überwacht und kommuniziert werden.",
    req: "Gefordert wird eine dokumentierte Zielliste mit messbaren BCM-Zielen (z.B. '100% der kritischen Prozesse haben einen definierten RTO'), Verantwortlichen, Terminen, Überwachungsmethode und Aktualisierungszyklus. Die Ziele müssen explizit mit der BCM-Politik verknüpft sein.",
    q: "Sind Ziele zur Aufrechterhaltung der Betriebsfähigkeit für relevante Funktionen/Ebenen festgelegt, messbar, überwacht, kommuniziert, bei Bedarf aktualisiert und als dokumentierte Information aufbewahrt?",
    hint: "Prüfen Sie: Zielkatalog mit KPIs, Reviewprotokolle.",
  },
  {
    id: "ISO22301-6.2.2",
    domain: "6. Planung",
    title: "Planung zur Zielerreichung",
    erl: "Für jedes BCM-Ziel muss ein konkreter Aktionsplan vorliegen, der festlegt: Was getan wird, welche Ressourcen benötigt werden, wer verantwortlich ist, bis wann und wie der Erfolg gemessen wird.",
    req: "Gefordert wird für jedes BCM-Ziel ein Aktionsplan, der die fünf Normfragen beantwortet: Was wird getan? Welche Ressourcen werden benötigt? Wer ist verantwortlich? Bis wann? Wie werden die Ergebnisse bewertet? Ein einfaches Projektmanagement-Tool oder eine Tabelle genügt.",
    q: "Ist für jedes Ziel festgelegt, was getan wird, welche Ressourcen erforderlich sind, wer verantwortlich ist, wann es abgeschlossen wird und wie die Ergebnisse bewertet werden?",
    hint: "Prüfen Sie: Massnahmen-/Projektplan je Ziel.",
  },
  {
    id: "ISO22301-6.3",
    domain: "6. Planung",
    title: "Planung von Änderungen am BCMS",
    erl: "Änderungen am BCMS müssen systematisch geplant werden. Vor der Umsetzung müssen Zweck, Risiken, Ressourcenbedarf und Verantwortlichkeiten der Änderung bewertet sein.",
    req: "Gefordert wird ein dokumentiertes Change-Management-Verfahren für das BCMS. Für jede signifikante Änderung muss eine Dokumentation vorliegen, die Zweck, Risikobeurteilung, Ressourcenbedarf und Verantwortlichkeiten beschreibt. Protokolle genehmigter Änderungen müssen aufbewahrt werden.",
    q: "Werden Änderungen am BCMS geplant durchgeführt, unter Berücksichtigung von Zweck und Folgen, Integrität des BCMS, Ressourcenverfügbarkeit sowie Zuweisung von Verantwortlichkeiten?",
    hint: "Prüfen Sie: Change-Management-Protokolle für das BCMS.",
  },

  // ── 7. Unterstützung ─────────────────────────────────────────────────────
  {
    id: "ISO22301-7.1",
    domain: "7. Unterstützung",
    title: "Ressourcen",
    erl: "Die Organisation muss die für das BCMS erforderlichen Ressourcen systematisch ermittelt haben und nachweisen, dass diese bereitgestellt werden – inkl. Ressourcen für Übungen und Weiterentwicklung.",
    req: "Gefordert wird eine Ressourcenplanung für das BCMS (z.B. Stellenplan, Budgetplanung, Infrastrukturplan). Genehmigte Budgets für BCM-Aktivitäten müssen nachweisbar sein. Fehlende Ressourcen müssen als Lücke erfasst und adressiert werden.",
    q: "Wurden die für Aufbau, Umsetzung, Aufrechterhaltung und fortlaufende Verbesserung des BCMS erforderlichen Ressourcen bestimmt und bereitgestellt?",
    hint: "Prüfen Sie: Budgetplanung, Personalplanung, Investitionsentscheide.",
  },
  {
    id: "ISO22301-7.2",
    domain: "7. Unterstützung",
    title: "Kompetenz",
    erl: "Für alle Personen mit BCM-relevanten Aufgaben muss die erforderliche Kompetenz bestimmt, sichergestellt und nachgewiesen sein. Bei Kompetenzlücken müssen Massnahmen ergriffen und deren Wirksamkeit überprüft werden.",
    req: "Gefordert wird eine Kompetenzmatrix mit allen BCM-relevanten Rollen und den jeweils erforderlichen Kompetenzen. Für jede Person muss ein Nachweis der Kompetenzerfüllung vorliegen (Schulungszeugnis, Zertifikat oder dokumentierter Erfahrungsnachweis). Lücken und Massnahmen zu deren Schliessung müssen dokumentiert sein.",
    q: "Ist die erforderliche Kompetenz für Personen mit BCM-relevanten Tätigkeiten bestimmt, sichergestellt, bei Bedarf durch Massnahmen erworben, und wird dies dokumentiert?",
    hint: "Prüfen Sie: Schulungsnachweise, Kompetenzmatrix, Zertifikate.",
  },
  {
    id: "ISO22301-7.3",
    domain: "7. Unterstützung",
    title: "Bewusstsein",
    erl: "Alle Mitarbeitenden müssen über die BCM-Politik, ihre eigene Rolle und die Konsequenzen einer Nichterfüllung informiert sein.",
    req: "Gefordert werden Nachweise eines BCM-Awareness-Programms: Schulungsunterlagen, Teilnehmerlisten, E-Learning-Abschlüsse oder Testergebnisse. Die Inhalte müssen die vier Normpunkte abdecken: BCM-Politik, eigener Beitrag zur BCMS-Wirksamkeit, Konsequenzen bei Nichterfüllung sowie eigene Rolle vor/während/nach Störungen.",
    q: "Sind sich die unter Aufsicht der Organisation tätigen Personen der BCM-Politik, ihres Beitrags, der Folgen einer Nichterfüllung sowie ihrer eigenen Rolle vor, während und nach Störungen bewusst?",
    hint: "Prüfen Sie: Awareness-Programme, Schulungsteilnahmequoten, Tests.",
  },
  {
    id: "ISO22301-7.4",
    domain: "7. Unterstützung",
    title: "Kommunikation",
    erl: "Ein Kommunikationsplan für das BCMS muss definieren, worüber, wann, mit wem, wie und durch wen kommuniziert wird – intern und extern.",
    req: "Gefordert wird eine Kommunikationsmatrix oder ein Kommunikationsplan, der für alle BCM-relevanten Themen Inhalt, Zeitpunkt, Empfängergruppen, Kanal und Absender definiert. Dies schliesst reguläre Kommunikation (z.B. Jahresbericht) und anlassbezogene Kommunikation (z.B. nach Übungen) ein.",
    q: "Ist festgelegt, worüber, wann, mit wem, wie und durch wen intern und extern zum BCMS kommuniziert wird?",
    hint: "Prüfen Sie: Kommunikationsplan, Eskalationswege.",
  },
  {
    id: "ISO22301-7.5.1",
    domain: "7. Unterstützung",
    title: "Dokumentierte Information – Allgemeines",
    erl: "Das BCMS muss alle von der Norm geforderten und alle von der Organisation selbst als notwendig erachteten dokumentierten Informationen enthalten.",
    req: "Gefordert wird ein Dokumentenverzeichnis (Master Document List) des BCMS, das alle geforderten und gewählten Dokumente aufführt. Alle von der Norm explizit verlangten Dokumente (Scope, Politik, BIA, Risikobeurteilung, BC-Pläne, Übungsberichte etc.) müssen nachweislich vorhanden sein.",
    q: "Enthält das BCMS sowohl die von der Norm geforderte als auch die von der Organisation selbst als notwendig bestimmte dokumentierte Information?",
    hint: "Prüfen Sie: Dokumentenlandkarte / -verzeichnis des BCMS.",
  },
  {
    id: "ISO22301-7.5.2",
    domain: "7. Unterstützung",
    title: "Erstellen und Aktualisieren",
    erl: "Alle BCMS-Dokumente müssen mit Titel, Datum, Version und Autor gekennzeichnet sein. Ein definierter Genehmigungs- und Aktualisierungsprozess muss existieren.",
    req: "Gefordert wird eine Dokumentvorlage oder ein Dokumentenmanagementsystem, das sicherstellt, dass alle BCMS-Dokumente Titel, Dokumentennummer/Version, Erstellungs-/Änderungsdatum, Autor und Genehmigungsvermerk tragen. Der Review- und Genehmigungsprozess muss schriftlich definiert sein.",
    q: "Werden beim Erstellen und Aktualisieren dokumentierter Information angemessene Kennzeichnung/Beschreibung, Format/Medium sowie Überprüfung und Genehmigung sichergestellt?",
    hint: "Prüfen Sie: Dokumentvorlagen, Versionshistorie, Freigabeworkflows.",
  },
  {
    id: "ISO22301-7.5.3",
    domain: "7. Unterstützung",
    title: "Lenkung dokumentierter Information",
    erl: "Alle BCMS-Dokumente müssen zentral verwaltet, gegen unbefugten Zugriff geschützt und jederzeit auffindbar sein. Verteilung, Versionskontrolle, Archivierung und externe Dokumente müssen geregelt sein.",
    req: "Gefordert wird ein Dokumentenmanagementsystem (papierbasiert oder elektronisch), das sicherstellt: aktuelle Versionen sind auffindbar und zugänglich, veraltete Versionen sind archiviert oder gelöscht, Zugriffsrechte sind geregelt, externe Dokumente sind als solche gekennzeichnet und änderungsüberwacht.",
    q: "Wird die für das BCMS erforderliche dokumentierte Information gelenkt, sodass sie verfügbar, geeignet und angemessen geschützt ist (inkl. Verteilung, Zugriff, Ablage, Versionskontrolle, Aufbewahrung)?",
    hint: "Prüfen Sie: Dokumentenmanagementsystem, Zugriffsrechte, Archivierungsregeln.",
  },

  // ── 8. Betrieb ───────────────────────────────────────────────────────────
  {
    id: "ISO22301-8.1",
    domain: "8. Betrieb",
    title: "Betriebliche Planung und Steuerung",
    erl: "Die Organisation muss nachweisen, dass alle BCM-relevanten Prozesse geplant, gesteuert und überwacht werden. Ausgegliederte Prozesse und die Lieferkette müssen aktiv gesteuert werden.",
    req: "Gefordert werden Prozessbeschreibungen oder Verfahrensanweisungen für alle BCM-relevanten Prozesse mit definierten Kriterien, sowie Nachweise der tatsächlichen Prozessdurchführung (Protokolle, Checklisten). Outsourcing-Verträge müssen BCM-relevante Klauseln (Notfallkontakte, RTO-Anforderungen, Auditrechte) enthalten.",
    q: "Werden die Prozesse zur Erfüllung der Anforderungen geplant, umgesetzt und gesteuert, werden Änderungen überwacht/bewertet, und werden ausgegliederte Prozesse sowie die Lieferkette gesteuert?",
    hint: "Prüfen Sie: Prozesssteuerungsdokumente, Outsourcing-Verträge mit BC-Klauseln.",
  },
  {
    id: "ISO22301-8.2.1",
    domain: "8. Betrieb",
    title: "BIA und Risikobeurteilung – Allgemeines",
    erl: "Die Organisation muss systematische, dokumentierte Prozesse für die Business-Impact-Analyse und die Risikobeurteilung etabliert haben, die periodisch überprüft werden.",
    req: "Gefordert werden eine schriftliche BIA-Methodik und eine Risikobeurteilungs-Methodik, die den verwendeten Ansatz, die Kriterien, die Bewertungsskalen und die Überprüfungsfrequenz beschreiben. Review-Protokolle müssen die periodische Überprüfung nachweisen.",
    q: "Sind systematische Prozesse zur Business-Impact-Analyse und Risikobeurteilung umgesetzt, und werden diese in geplanten Abständen sowie bei signifikanten Änderungen überprüft?",
    hint: "Prüfen Sie: BIA-/Risikobeurteilungs-Methodik, Review-Historie.",
  },
  {
    id: "ISO22301-8.2.2.a",
    domain: "8. Betrieb",
    title: "Business-Impact-Analyse – Methodik, MTPD/RTO",
    erl: "Die BIA muss für alle kritischen Tätigkeiten die maximal zulässige Störungsdauer (MTPD) und den Wiederherstellungszeitpunkt (RTO) mit Mindestkapazität bestimmt haben.",
    req: "Gefordert wird ein BIA-Bericht, der für jede kritische Tätigkeit dokumentiert: Einflussarten (finanziell, reputatorisch, regulatorisch, operativ), maximale Störungsdauer (MTPD) und Wiederherstellungszeitpunkt mit Mindestkapazität (RTO). Die Einflussarten und -kriterien müssen vor der Analyse schriftlich definiert worden sein.",
    q: "Werden im Rahmen der BIA Einflussarten/-kriterien festgelegt, Tätigkeiten ermittelt sowie MTPD und RTO für die Wiederaufnahme mit Mindestkapazität bestimmt?",
    hint: "Prüfen Sie: BIA-Berichte mit MTPD/RTO-Werten je Tätigkeit.",
  },
  {
    id: "ISO22301-8.2.2.b",
    domain: "8. Betrieb",
    title: "Business-Impact-Analyse – Betriebstätigkeiten hoher Priorität & Ressourcen",
    erl: "Auf Basis der BIA müssen Betriebstätigkeiten hoher Priorität identifiziert und deren Ressourcenbedarf sowie alle Abhängigkeiten dokumentiert sein.",
    req: "Gefordert wird eine priorisierte Liste der Betriebstätigkeiten hoher Priorität. Für jede Tätigkeit müssen dokumentiert sein: benötigte Ressourcen (Personal mit Anzahl und Qualifikation, IT-Systeme, Infrastruktur, Ausrüstung), Abhängigkeiten von internen Prozessen, externen Lieferanten und Partnern sowie Wechselbeziehungen zwischen den Tätigkeiten.",
    q: "Werden auf Basis der BIA Betriebstätigkeiten hoher Priorität ermittelt, Ressourcen bestimmt und Abhängigkeiten (inkl. Partner und Lieferanten) sowie Wechselbeziehungen festgelegt?",
    hint: "Prüfen Sie: Liste der Betriebstätigkeiten hoher Priorität, Ressourcen- und Abhängigkeitsmatrix.",
  },
  {
    id: "ISO22301-8.2.3",
    domain: "8. Betrieb",
    title: "Risikobeurteilung",
    erl: "Für alle Betriebstätigkeiten hoher Priorität und deren Ressourcen muss eine Risikobeurteilung durchgeführt worden sein, und Risiken mit Behandlungsbedarf müssen ausgewiesen werden.",
    req: "Gefordert wird ein operatives Risikoregister für Störungsrisiken. Für jede Betriebstätigkeit hoher Priorität und deren Ressourcen müssen die Risiken identifiziert, anhand einer definierten Skala (z.B. Wahrscheinlichkeit × Auswirkung) bewertet und nach Behandlungsbedarf priorisiert sein.",
    q: "Werden Risiken einer Störung der Betriebstätigkeiten hoher Priorität und der erforderlichen Ressourcen ermittelt, analysiert, bewertet und wird bestimmt, welche Risiken eine Behandlung erfordern?",
    hint: "Prüfen Sie: Risikoregister mit Bezug zu Betriebstätigkeiten hoher Priorität.",
  },
  {
    id: "ISO22301-8.3.1",
    domain: "8. Betrieb",
    title: "Strategien und Lösungen – Allgemeines",
    erl: "Die Organisation muss auf Basis der BIA- und Risikobeurteilungsergebnisse BC-Strategien entwickelt und ausgewählt haben, die alle drei Phasen abdecken.",
    req: "Gefordert wird ein BC-Strategiedokument, das die gewählten Strategien auf Basis der BIA- und Risikoergebnisse beschreibt. Die Strategien müssen Optionen für alle drei Phasen abdecken: Vorbeugung (vor einer Störung), Reaktion (während einer Störung) und Wiederherstellung (nach einer Störung). Jede Strategie muss aus einer oder mehreren konkreten Lösungen bestehen.",
    q: "Wurden Strategien zur Aufrechterhaltung der Betriebsfähigkeit auf Grundlage der BIA- und Risikobeurteilungsergebnisse ermittelt und ausgewählt, die Optionen vor, während und nach einer Störung berücksichtigen?",
    hint: "Prüfen Sie: Strategiedokument mit Optionsbewertung.",
  },
  {
    id: "ISO22301-8.3.2",
    domain: "8. Betrieb",
    title: "Identifizierung der Strategien und Lösungen",
    erl: "Bei der Identifizierung von BC-Strategien und -Lösungen muss systematisch bewertet werden, inwieweit diese Tätigkeiten hoher Priorität fortführen/wiederherstellen, schützen, die Störungswahrscheinlichkeit/-dauer reduzieren und Ressourcen sicherstellen.",
    req: "Gefordert wird eine Bewertungsmatrix, die verschiedene Lösungsoptionen anhand der sechs Normkriterien bewertet: Tätigkeiten fortführen/wiederherstellen, Tätigkeiten schützen, Störungswahrscheinlichkeit reduzieren, Störungsdauer verkürzen, Auswirkung begrenzen, Ressourcen sicherstellen.",
    q: "Erfolgt die Identifizierung von Strategien/Lösungen anhand des Umfangs, in dem sie Tätigkeiten hoher Priorität fortführen/wiederherstellen, schützen, die Wahrscheinlichkeit/Dauer einer Störung reduzieren, die Auswirkung begrenzen und Ressourcen sicherstellen?",
    hint: "Prüfen Sie: Bewertungsmatrix der Lösungsoptionen.",
  },
  {
    id: "ISO22301-8.3.3",
    domain: "8. Betrieb",
    title: "Auswahl der Strategien und Lösungen",
    erl: "Die Auswahl der BC-Strategien muss nachvollziehbar begründet sein, unter Abwägung von Risikotoleranz, Kosten und Nutzen.",
    req: "Gefordert wird eine Entscheidungsvorlage oder ein Auswahlbericht, der dokumentiert, warum die gewählten Strategien ausgewählt wurden. Kosten-Nutzen-Überlegungen und die Risikotoleranz der Organisation müssen in der Begründung erkennbar sein. Die Genehmigung durch die Leitung muss nachweisbar sein.",
    q: "Erfolgt die Auswahl der Strategien/Lösungen unter Berücksichtigung der Anforderungen, des akzeptablen Risikoumfangs sowie der damit verbundenen Kosten und Nutzen?",
    hint: "Prüfen Sie: Entscheidungsvorlagen, Kosten-Nutzen-Analysen.",
  },
  {
    id: "ISO22301-8.3.4",
    domain: "8. Betrieb",
    title: "Ressourcenbedarf für Lösungen",
    erl: "Für jede gewählte BC-Lösung muss der vollständige Ressourcenbedarf bestimmt sein (Personal, Daten, Infrastruktur, Ausrüstung, ICT, Transport, Finanzen, Partner).",
    req: "Gefordert wird eine Ressourcenliste für jede gewählte BC-Lösung, die alle acht Normkategorien abdeckt: Personal (mit Anzahl und Qualifikation), Informationen/Daten, materielle Infrastruktur, Ausrüstung/Verbrauchsmittel, ICT-Systeme, Transport/Logistik, Finanzen sowie Partner und Lieferanten. Der Bedarf muss quantifiziert sein.",
    q: "Wurde der Ressourcenbedarf zur Umsetzung der gewählten Lösungen bestimmt (Personen, Informationen/Daten, Infrastruktur, Ausrüstung, ICT-Systeme, Transport/Logistik, Finanzen, Partner/Lieferanten)?",
    hint: "Prüfen Sie: Ressourcenplanung je Lösung.",
  },
  {
    id: "ISO22301-8.3.5",
    domain: "8. Betrieb",
    title: "Umsetzung von Lösungen",
    erl: "Alle gewählten BC-Lösungen müssen tatsächlich umgesetzt und so aufrechterhalten sein, dass sie im Bedarfsfall aktiviert werden können.",
    req: "Gefordert werden Implementierungsnachweise für alle gewählten Lösungen (z.B. unterzeichnete Ausweichverträge, Systemkonfigurationsdokumentationen, Ausrüstungsbestandslisten, Aktivierungstestberichte). Wartungs- und Bereitschaftspläne für die Lösungen müssen vorhanden und aktuell sein.",
    q: "Werden die ausgewählten Lösungen zur Aufrechterhaltung der Betriebsfähigkeit umgesetzt und so aufrechterhalten, dass sie bei Bedarf aktiviert werden können?",
    hint: "Prüfen Sie: Implementierungsnachweise, Aktivierungstests.",
  },
  {
    id: "ISO22301-8.4.1",
    domain: "8. Betrieb",
    title: "Pläne und Verfahren – Allgemeines",
    erl: "Die Organisation muss eine Reaktionsstruktur und dokumentierte BC-Pläne und -Verfahren haben, die bei Störungen aktiviert werden und präzise, flexibel und mit klaren Rollen versehen sind.",
    req: "Gefordert wird eine Übersicht aller BC-Pläne und Reaktionsverfahren mit Verweisen auf die Einzeldokumente. Alle Verfahren müssen schriftlich festgelegt, versionskontrolliert und für die Reaktionsteams jederzeit zugänglich sein – auch bei IT-Ausfall (z.B. als Druckversion).",
    q: "Ist eine Reaktionsstruktur umgesetzt, die zeitnahe Warnung und Kommunikation ermöglicht, und stehen Pläne/Verfahren zur Steuerung der Organisation während einer Störung bereit?",
    hint: "Prüfen Sie: Übersicht der BC-Pläne und Reaktionsverfahren.",
  },
  {
    id: "ISO22301-8.4.2.a",
    domain: "8. Betrieb",
    title: "Reaktionsstruktur – Teams",
    erl: "Ein oder mehrere Reaktionsteams mit definierten Rollen, Verantwortlichkeiten, Befugnissen und Stellvertretungen müssen eingerichtet sein.",
    req: "Gefordert werden Organigramme oder Strukturpläne der Reaktionsteams mit benannten Personen und Stellvertretern sowie Rollenbeschreibungen mit Verantwortlichkeiten und Befugnissen. Für jedes Team müssen Aktivierungs-, Betriebs-, Koordinations- und Kommunikationsverfahren schriftlich vorliegen.",
    q: "Sind eine Struktur und ein oder mehrere Teams für die Reaktion auf Störungen umgesetzt, Rollen/Verantwortlichkeiten klar beschrieben und jedes Team mit kompetentem Personal sowie dokumentierten Verfahren ausgestattet?",
    hint: "Prüfen Sie: Teamstruktur, Stellvertreterregelungen, Verfahrensdokumente.",
  },
  {
    id: "ISO22301-8.4.2.b",
    domain: "8. Betrieb",
    title: "Reaktionsstruktur – Fähigkeiten der Teams",
    erl: "Die Reaktionsteams müssen zusammen in der Lage sein, den gesamten Reaktionszyklus zu bewältigen: Lagebeurteilung, Auslösung, Priorisierung, Überwachung, Aktivierung und Kommunikation.",
    req: "Gefordert werden validierte Teambefähigungen (Nachweis durch Übungen). Eskalationsschwellen und Auslösekriterien für die formale Reaktion müssen schriftlich definiert und allen Teammitgliedern bekannt sein. Ein expliziter Priorisierungsrahmen (Menschenleben zuerst) muss in den Verfahren verankert sein.",
    q: "Sind die Teams zusammen in der Lage, Störungen zu beurteilen, Reaktionen auszulösen, Massnahmen zu priorisieren, Auswirkungen zu überwachen, Lösungen zu aktivieren und mit Parteien, Behörden und Medien zu kommunizieren?",
    hint: "Prüfen Sie: Eskalationsschwellen, Übungsberichte zur Teamreaktion.",
  },
  {
    id: "ISO22301-8.4.3.a",
    domain: "8. Betrieb",
    title: "Warnung und Kommunikation – Verfahren",
    erl: "Dokumentierte Kommunikationsverfahren müssen interne/externe Kommunikation, Empfang von Meldungen, Kommunikationsmittel, Notfallhelfer, Medienmanagement und Störungsdokumentation regeln.",
    req: "Gefordert wird ein Kommunikationsverfahren für Störungssituationen. Es muss für alle relevanten Stakeholder-Gruppen (intern, Kunden, Behörden, Medien, Notfallhelfer) definieren: Was wird kommuniziert, wann, durch wen und über welchen Kanal. Ein aktuelles Kontaktverzeichnis mit Notfallkontakten und ein Störungsprotokoll-Template müssen vorliegen.",
    q: "Sind Verfahren dokumentiert für interne/externe Kommunikation, Empfang von Mitteilungen, verfügbare Kommunikationsmittel, Kommunikation mit Notfallhelfern, Medienanfragen sowie Aufzeichnung von Störungsdetails?",
    hint: "Prüfen Sie: Kommunikationsverfahren, Medien-/Krisenkommunikationsplan.",
  },
  {
    id: "ISO22301-8.4.3.b",
    domain: "8. Betrieb",
    title: "Warnung und Kommunikation – Ergänzende Massnahmen & Übung",
    erl: "Warnmeldungen an betroffene Parteien und die Koordination mit anderen Organisationen müssen geregelt und die Kommunikationsverfahren regelmässig geübt sein.",
    req: "Gefordert wird ein Warnmeldesystem oder -verfahren für die Benachrichtigung betroffener Stakeholder. Verfahren zur Koordination mit anderen Organisationen (z.B. Behörden) müssen definiert sein. Übungsberichte müssen bestätigen, dass Kommunikationsverfahren im Rahmen des Übungsprogramms durchgeführt wurden.",
    q: "Werden Warnmeldungen an potenziell betroffene Parteien herausgegeben, Koordination mit anderen Organisationen sichergestellt, und werden die Warn-/Kommunikationsverfahren im Übungsprogramm durchgeführt?",
    hint: "Prüfen Sie: Übungsberichte zu Warn-/Kommunikationsverfahren.",
  },
  {
    id: "ISO22301-8.4.4.a",
    domain: "8. Betrieb",
    title: "BC-Pläne – Gesamtinhalt",
    erl: "Die Gesamtheit der BC-Pläne muss alle Normanforderungen abdecken: Massnahmen, Überwachung, Aktivierungsschwellen, Belieferungsverfahren sowie Massnahmen zum Personen- und Umweltschutz.",
    req: "Gefordert wird der gesamte Dokumentensatz aller BC-Pläne, der inhaltlich alle Anforderungen von 8.4.4.2 abdeckt. Eine Checkliste gegen die normativen Anforderungen (a bis d) muss die Vollständigkeit belegen. Alle Pläne müssen aktuell, genehmigt und in ihrer aktuellen Version verfügbar sein.",
    q: "Enthalten die Pläne insgesamt Massnahmen zur Fortsetzung/Wiederherstellung, Verweis auf Schwellenwerte/Aktivierungsprozess, Verfahren zur Belieferung mit vereinbarter Kapazität sowie Steuerung unmittelbarer Auswirkungen?",
    hint: "Prüfen Sie: BC-Pläne auf Vollständigkeit gemäss 8.4.4.2.",
  },
  {
    id: "ISO22301-8.4.4.b",
    domain: "8. Betrieb",
    title: "BC-Pläne – Einzelplan-Inhalt",
    erl: "Jeder einzelne BC-Plan muss alle acht Pflichtelemente der Norm enthalten und am Einsatzort verfügbar sein.",
    req: "Gefordert wird jeder einzelne BC-Plan als eigenständiges Dokument mit allen acht Elementen von 8.4.4.3: Zweck/Scope/Ziele, Rollen und Verantwortlichkeiten, Massnahmen zur Lösungsumsetzung, Aktivierungsinformationen (inkl. Aktivierungskriterien), interne/externe Wechselbeziehungen, Ressourcenanforderungen, Berichterstattungsanforderungen und Beendigungsprozess. Der Plan muss offline/ausgedruckt am Einsatzort verfügbar sein.",
    q: "Enthält jeder einzelne Plan Zweck/Scope/Ziele, Rollen, Massnahmen, Aktivierungsinformationen, Wechselbeziehungen, Ressourcenanforderungen, Berichterstattungsanforderungen und Beendigungsprozess, und ist er am benötigten Ort verfügbar?",
    hint: "Prüfen Sie: Stichprobe einzelner BC-Pläne gegen die Checkliste 8.4.4.3.",
  },
  {
    id: "ISO22301-8.4.5",
    domain: "8. Betrieb",
    title: "Wiederherstellung",
    erl: "Dokumentierte Prozesse für die geordnete Rückkehr vom Notbetrieb zum Normalbetrieb müssen vorhanden sein.",
    req: "Gefordert werden dokumentierte Wiederherstellungsverfahren, die definieren: Wann und anhand welcher Kriterien der Notbetrieb beendet wird, wie und in welcher Reihenfolge die normalen Prozesszustände wiederhergestellt werden und wer die Entscheidung zur Rückkehr trifft und umsetzt.",
    q: "Verfügt die Organisation über dokumentierte Prozesse zur Wiederherstellung und Rückkehr der Geschäftstätigkeiten aus den vorübergehend eingeführten Massnahmen nach einer Störung?",
    hint: "Prüfen Sie: Wiederherstellungs-/Rückkehrverfahren.",
  },
  {
    id: "ISO22301-8.5",
    domain: "8. Betrieb",
    title: "Übungsprogramm",
    erl: "Ein systematisches Übungsprogramm muss existieren, durchgeführt werden und nach jeder Übung zu dokumentierten Massnahmen führen.",
    req: "Gefordert wird ein Übungsplan für mindestens 12 Monate im Voraus (inkl. Szenarien, Ziele, Verantwortliche, Teilnehmer). Nach jeder Übung muss ein formalisierter Übungsbericht mit Ergebnissen, Erkenntnissen und Massnahmen erstellt werden. Die Umsetzung der Massnahmen aus früheren Übungen muss nachverfolgt werden.",
    q: "Wird ein Übungs- und Überprüfungsprogramm umgesetzt, das Szenarien nutzt, Teamwork/Kompetenz entwickelt, die Strategien/Lösungen validiert, Berichte erzeugt und in geplanten Abständen durchgeführt wird?",
    hint: "Prüfen Sie: Übungsplan, Übungsberichte, Massnahmen aus Lessons Learned.",
  },
  {
    id: "ISO22301-8.6",
    domain: "8. Betrieb",
    title: "Bewertung der Dokumentation und Fähigkeiten",
    erl: "Die Organisation muss systematisch und periodisch die Eignung und Wirksamkeit aller BCM-Elemente bewerten, inkl. Partner/Lieferanten und Compliance-Prüfung.",
    req: "Gefordert werden periodische Bewertungsberichte zur Eignung und Wirksamkeit der BCM-Elemente (BIA, Risikobeurteilung, Strategien, Pläne, Verfahren). Für Partner/Lieferanten mit BCM-Relevanz müssen Fähigkeitsbewertungen dokumentiert sein. Eine Compliance-Checkliste muss die Einhaltung rechtlicher Vorgaben und eigener BCM-Ziele belegen.",
    q: "Werden Eignung, Angemessenheit und Wirksamkeit von BIA, Risikobeurteilung, Strategien, Lösungen, Plänen und Verfahren bewertet, Partner/Lieferanten bewertet, Compliance geprüft und Dokumentation zeitnah aktualisiert?",
    hint: "Prüfen Sie: Bewertungsberichte, Aktualisierungsnachweise.",
  },

  // ── 9. Bewertung der Leistung ────────────────────────────────────────────
  {
    id: "ISO22301-9.1",
    domain: "9. Bewertung der Leistung",
    title: "Überwachung, Messung, Analyse und Bewertung",
    erl: "Die Organisation muss definiert haben, was, wie, wann und von wem gemessen wird, und die Leistung und Wirksamkeit des BCMS bewerten.",
    req: "Gefordert wird ein KPI-Katalog oder Messkatalog für das BCMS. Für jeden Indikator müssen definiert sein: Was wird gemessen, Methode, Messhäufigkeit, Verantwortlicher und Zielwert. Messberichte oder Dashboards müssen regelmässig erstellt und aufbewahrt werden.",
    q: "Ist bestimmt, was überwacht/gemessen wird, welche Methoden angewendet werden, wann und von wem dies erfolgt, wird dies dokumentiert, und wird die Leistung und Wirksamkeit des BCMS bewertet?",
    hint: "Prüfen Sie: KPI-Katalog, Messberichte.",
  },
  {
    id: "ISO22301-9.2.1",
    domain: "9. Bewertung der Leistung",
    title: "Internes Audit – Allgemeines",
    erl: "Die Organisation muss interne Audits in definierten Abständen durchführen, die die BCMS-Konformität und Wirksamkeit prüfen.",
    req: "Gefordert werden interne Auditberichte aus den letzten 12 Monaten. Jeder Auditbericht muss Auditkriterien, Auditumfang, Methodik, Feststellungen, Nichtkonformitäten und eingeleitete Korrekturmassnahmen dokumentieren. Ein Zeitplan für künftige Audits muss vorhanden sein.",
    q: "Werden in geplanten Abständen interne Audits durchgeführt, um festzustellen, ob das BCMS die eigenen Anforderungen sowie die Normanforderungen erfüllt und wirksam aufrechterhalten wird?",
    hint: "Prüfen Sie: Auditberichte, Auditzyklus.",
  },
  {
    id: "ISO22301-9.2.2",
    domain: "9. Bewertung der Leistung",
    title: "Auditprogramm(e)",
    erl: "Ein dokumentiertes Auditprogramm muss existieren, mit unabhängigen Auditoren und einer Massnahmenverfolgung.",
    req: "Gefordert wird ein dokumentiertes Auditprogramm für mindestens 12 Monate (Termine, Umfang, Auditoren, Methoden). Qualifikationsnachweise der Auditoren oder ein Nachweis ihrer Unabhängigkeit müssen vorhanden sein. Eine Massnahmenverfolgungsliste aus früheren Audits mit Nachweis der Umsetzung und Verifikation muss geführt werden.",
    q: "Sind Auditprogramme geplant/aufgebaut, Auditkriterien/-umfang festgelegt, Objektivität der Auditoren sichergestellt, Ergebnisse berichtet, Information aufbewahrt und Korrekturmassnahmen samt Verifizierung sichergestellt?",
    hint: "Prüfen Sie: Auditprogramm, Auditorenqualifikation, Nachweis der Massnahmenverfolgung.",
  },
  {
    id: "ISO22301-9.3.1",
    domain: "9. Bewertung der Leistung",
    title: "Managementbewertung – Allgemeines",
    erl: "Die oberste Leitung muss das BCMS in definierten Abständen formal bewerten. Protokolle dieser Bewertungen müssen vorliegen.",
    req: "Gefordert werden Protokolle der Managementbewertungen mit Datum, Teilnehmern, behandelten Themen und gefassten Beschlüssen. Die Managementbewertung muss in einem definierten Rhythmus (empfohlen: mindestens jährlich) durchgeführt werden.",
    q: "Bewertet die oberste Leitung das BCMS in geplanten Abständen, um dessen fortdauernde Eignung, Angemessenheit und Wirksamkeit sicherzustellen?",
    hint: "Prüfen Sie: Termine/Protokolle der Managementbewertung.",
  },
  {
    id: "ISO22301-9.3.2",
    domain: "9. Bewertung der Leistung",
    title: "Eingaben für die Managementbewertung",
    erl: "Die Managementbewertung muss alle elf von der Norm geforderten Eingaben (9.3.2 a–k) behandeln.",
    req: "Gefordert wird, dass das Protokoll der Managementbewertung nachweislich alle elf Eingabepunkte gemäss 9.3.2 (a bis k) behandelt: Status früherer Massnahmen, Kontextveränderungen, BCMS-Leistungsdaten, Stakeholder-Rückmeldungen, Änderungsbedarf, Verbesserungsmöglichkeiten, BIA/Risiko-Informationen, Ergebnisse aus 8.6, unbehandelte Risiken, Erfahrungen aus Störungen sowie Verbesserungsmöglichkeiten. Eine strukturierte Traktandenliste muss diese Punkte abdecken.",
    q: "Behandelt die Managementbewertung Status früherer Massnahmen, Kontextveränderungen, BCMS-Leistungsinformationen, Stakeholder-Rückmeldungen, Änderungsbedarf, Verbesserungsmöglichkeiten, BIA/Risikoinformationen, Ergebnisse aus 8.6 sowie Erfahrungen aus Störungen?",
    hint: "Prüfen Sie: Vollständige Traktandenliste/Unterlagen der Managementbewertung gegen 9.3.2 a)–k).",
  },
  {
    id: "ISO22301-9.3.3",
    domain: "9. Bewertung der Leistung",
    title: "Ergebnisse der Managementbewertung",
    erl: "Die Managementbewertung muss zu konkreten Entscheidungen und Massnahmen führen, die dokumentiert, kommuniziert und verfolgt werden.",
    req: "Gefordert wird ein Protokoll der Managementbewertung mit klaren Beschlüssen, Verantwortlichen und Terminen. Eine Massnahmenliste aus der Managementbewertung muss geführt und deren Umsetzung verfolgt werden. Ein Nachweis der Kommunikation der Ergebnisse an relevante Stakeholder muss vorliegen.",
    q: "Enthalten die Ergebnisse der Managementbewertung Entscheidungen zu Verbesserungen und Änderungsbedarf am BCMS, wird Information aufbewahrt und werden Ergebnisse mitgeteilt und Massnahmen ergriffen?",
    hint: "Prüfen Sie: Protokoll/Beschlüsse der Managementbewertung, Nachweis der Kommunikation.",
  },

  // ── 10. Verbesserung ─────────────────────────────────────────────────────
  {
    id: "ISO22301-10.1",
    domain: "10. Verbesserung",
    title: "Nichtkonformität und Korrekturmassnahmen",
    erl: "Bei jeder Nichtkonformität muss die Organisation reagieren, Ursachen analysieren, Korrekturmassnahmen einleiten und deren Wirksamkeit prüfen. Ein CAPA-Register muss geführt werden.",
    req: "Gefordert wird ein CAPA-Register (Corrective and Preventive Actions). Für jede Nichtkonformität müssen dokumentiert sein: Beschreibung, Ursachenanalyse (Rootcause), eingeleitete Massnahmen, Verantwortlicher, Termin und Ergebnis der Wirksamkeitsprüfung. Die Verhältnismässigkeit der Korrekturmassnahmen zur Schwere der Nichtkonformität muss erkennbar sein.",
    q: "Werden bei Nichtkonformitäten Sofortmassnahmen ergriffen, Ursachen bewertet und beseitigt, Wirksamkeit der Korrekturmassnahmen geprüft, das BCMS bei Bedarf angepasst und Information aufbewahrt?",
    hint: "Prüfen Sie: Nichtkonformitäten-/CAPA-Register.",
  },
  {
    id: "ISO22301-10.2",
    domain: "10. Verbesserung",
    title: "Fortlaufende Verbesserung",
    erl: "Die Organisation muss einen systematischen Ansatz zur kontinuierlichen Verbesserung des BCMS verfolgen, der auf Messdaten, Audits, Managementbewertungen und Lessons Learned basiert.",
    req: "Gefordert wird ein Verbesserungsregister oder -plan, der identifizierte Verbesserungsmöglichkeiten, Priorisierung, Massnahmen, Verantwortliche und Status aufführt. Die Verbindung zwischen Verbesserungen und deren Grundlagen (Messergebnisse, Audits, Managementbewertung, Übungsberichte, Störungsauswertungen) muss nachvollziehbar dokumentiert sein.",
    q: "Verbessert die Organisation Eignung, Angemessenheit und Wirksamkeit des BCMS fortlaufend auf Grundlage qualitativer und quantitativer Massnahmen, unter Berücksichtigung von Analyse/Bewertung und Managementbewertung?",
    hint: "Prüfen Sie: Verbesserungsregister, Trendanalysen über mehrere Zyklen.",
  },
];
